import type { AirportOption } from "./types";

/** Static list of major world airports for autocomplete (no API call needed). */
export const AIRPORTS: AirportOption[] = [
  // ── Taiwan ──────────────────────────────────────────
  { iataCode: "TPE", name: "Taiwan Taoyuan International Airport", cityName: "Taipei", countryCode: "TW", countryName: "Taiwan" },
  { iataCode: "TSA", name: "Taipei Songshan Airport", cityName: "Taipei", countryCode: "TW", countryName: "Taiwan" },
  { iataCode: "KHH", name: "Kaohsiung International Airport", cityName: "Kaohsiung", countryCode: "TW", countryName: "Taiwan" },
  // ── East Asia ───────────────────────────────────────
  { iataCode: "NRT", name: "Narita International Airport", cityName: "Tokyo", countryCode: "JP", countryName: "Japan" },
  { iataCode: "HND", name: "Tokyo Haneda Airport", cityName: "Tokyo", countryCode: "JP", countryName: "Japan" },
  { iataCode: "KIX", name: "Kansai International Airport", cityName: "Osaka", countryCode: "JP", countryName: "Japan" },
  { iataCode: "ITM", name: "Osaka Itami Airport", cityName: "Osaka", countryCode: "JP", countryName: "Japan" },
  { iataCode: "FUK", name: "Fukuoka Airport", cityName: "Fukuoka", countryCode: "JP", countryName: "Japan" },
  { iataCode: "CTS", name: "New Chitose Airport", cityName: "Sapporo", countryCode: "JP", countryName: "Japan" },
  { iataCode: "NGO", name: "Chubu Centrair International Airport", cityName: "Nagoya", countryCode: "JP", countryName: "Japan" },
  { iataCode: "OKA", name: "Naha Airport", cityName: "Okinawa", countryCode: "JP", countryName: "Japan" },
  { iataCode: "ICN", name: "Incheon International Airport", cityName: "Seoul", countryCode: "KR", countryName: "South Korea" },
  { iataCode: "GMP", name: "Gimpo International Airport", cityName: "Seoul", countryCode: "KR", countryName: "South Korea" },
  { iataCode: "PUS", name: "Gimhae International Airport", cityName: "Busan", countryCode: "KR", countryName: "South Korea" },
  { iataCode: "HKG", name: "Hong Kong International Airport", cityName: "Hong Kong", countryCode: "HK", countryName: "Hong Kong" },
  { iataCode: "PVG", name: "Shanghai Pudong International Airport", cityName: "Shanghai", countryCode: "CN", countryName: "China" },
  { iataCode: "SHA", name: "Shanghai Hongqiao International Airport", cityName: "Shanghai", countryCode: "CN", countryName: "China" },
  { iataCode: "PEK", name: "Beijing Capital International Airport", cityName: "Beijing", countryCode: "CN", countryName: "China" },
  { iataCode: "PKX", name: "Beijing Daxing International Airport", cityName: "Beijing", countryCode: "CN", countryName: "China" },
  { iataCode: "CAN", name: "Guangzhou Baiyun International Airport", cityName: "Guangzhou", countryCode: "CN", countryName: "China" },
  { iataCode: "SZX", name: "Shenzhen Bao'an International Airport", cityName: "Shenzhen", countryCode: "CN", countryName: "China" },
  { iataCode: "CTU", name: "Chengdu Shuangliu International Airport", cityName: "Chengdu", countryCode: "CN", countryName: "China" },
  { iataCode: "XIY", name: "Xi'an Xianyang International Airport", cityName: "Xi'an", countryCode: "CN", countryName: "China" },
  { iataCode: "MFM", name: "Macau International Airport", cityName: "Macau", countryCode: "MO", countryName: "Macau" },
  // ── Southeast Asia ──────────────────────────────────
  { iataCode: "BKK", name: "Suvarnabhumi Airport", cityName: "Bangkok", countryCode: "TH", countryName: "Thailand" },
  { iataCode: "DMK", name: "Don Mueang International Airport", cityName: "Bangkok", countryCode: "TH", countryName: "Thailand" },
  { iataCode: "HKT", name: "Phuket International Airport", cityName: "Phuket", countryCode: "TH", countryName: "Thailand" },
  { iataCode: "CNX", name: "Chiang Mai International Airport", cityName: "Chiang Mai", countryCode: "TH", countryName: "Thailand" },
  { iataCode: "SIN", name: "Singapore Changi Airport", cityName: "Singapore", countryCode: "SG", countryName: "Singapore" },
  { iataCode: "KUL", name: "Kuala Lumpur International Airport", cityName: "Kuala Lumpur", countryCode: "MY", countryName: "Malaysia" },
  { iataCode: "CGK", name: "Soekarno-Hatta International Airport", cityName: "Jakarta", countryCode: "ID", countryName: "Indonesia" },
  { iataCode: "DPS", name: "Ngurah Rai International Airport", cityName: "Bali", countryCode: "ID", countryName: "Indonesia" },
  { iataCode: "MNL", name: "Ninoy Aquino International Airport", cityName: "Manila", countryCode: "PH", countryName: "Philippines" },
  { iataCode: "CEB", name: "Mactan–Cebu International Airport", cityName: "Cebu", countryCode: "PH", countryName: "Philippines" },
  { iataCode: "SGN", name: "Tan Son Nhat International Airport", cityName: "Ho Chi Minh City", countryCode: "VN", countryName: "Vietnam" },
  { iataCode: "HAN", name: "Noi Bai International Airport", cityName: "Hanoi", countryCode: "VN", countryName: "Vietnam" },
  { iataCode: "DAD", name: "Da Nang International Airport", cityName: "Da Nang", countryCode: "VN", countryName: "Vietnam" },
  { iataCode: "RGN", name: "Yangon International Airport", cityName: "Yangon", countryCode: "MM", countryName: "Myanmar" },
  { iataCode: "PNH", name: "Phnom Penh International Airport", cityName: "Phnom Penh", countryCode: "KH", countryName: "Cambodia" },
  // ── South Asia ──────────────────────────────────────
  { iataCode: "DEL", name: "Indira Gandhi International Airport", cityName: "New Delhi", countryCode: "IN", countryName: "India" },
  { iataCode: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", cityName: "Mumbai", countryCode: "IN", countryName: "India" },
  { iataCode: "BLR", name: "Kempegowda International Airport", cityName: "Bangalore", countryCode: "IN", countryName: "India" },
  { iataCode: "MAA", name: "Chennai International Airport", cityName: "Chennai", countryCode: "IN", countryName: "India" },
  { iataCode: "CMB", name: "Bandaranaike International Airport", cityName: "Colombo", countryCode: "LK", countryName: "Sri Lanka" },
  { iataCode: "DAC", name: "Hazrat Shahjalal International Airport", cityName: "Dhaka", countryCode: "BD", countryName: "Bangladesh" },
  { iataCode: "KTM", name: "Tribhuvan International Airport", cityName: "Kathmandu", countryCode: "NP", countryName: "Nepal" },
  // ── Middle East ─────────────────────────────────────
  { iataCode: "DXB", name: "Dubai International Airport", cityName: "Dubai", countryCode: "AE", countryName: "United Arab Emirates" },
  { iataCode: "AUH", name: "Abu Dhabi International Airport", cityName: "Abu Dhabi", countryCode: "AE", countryName: "United Arab Emirates" },
  { iataCode: "DOH", name: "Hamad International Airport", cityName: "Doha", countryCode: "QA", countryName: "Qatar" },
  { iataCode: "IST", name: "Istanbul Airport", cityName: "Istanbul", countryCode: "TR", countryName: "Turkey" },
  { iataCode: "SAW", name: "Istanbul Sabiha Gökçen International Airport", cityName: "Istanbul", countryCode: "TR", countryName: "Turkey" },
  { iataCode: "TLV", name: "Ben Gurion International Airport", cityName: "Tel Aviv", countryCode: "IL", countryName: "Israel" },
  // ── Europe ──────────────────────────────────────────
  { iataCode: "LHR", name: "London Heathrow Airport", cityName: "London", countryCode: "GB", countryName: "United Kingdom" },
  { iataCode: "LGW", name: "London Gatwick Airport", cityName: "London", countryCode: "GB", countryName: "United Kingdom" },
  { iataCode: "STN", name: "London Stansted Airport", cityName: "London", countryCode: "GB", countryName: "United Kingdom" },
  { iataCode: "CDG", name: "Charles de Gaulle Airport", cityName: "Paris", countryCode: "FR", countryName: "France" },
  { iataCode: "ORY", name: "Paris Orly Airport", cityName: "Paris", countryCode: "FR", countryName: "France" },
  { iataCode: "AMS", name: "Amsterdam Airport Schiphol", cityName: "Amsterdam", countryCode: "NL", countryName: "Netherlands" },
  { iataCode: "FRA", name: "Frankfurt Airport", cityName: "Frankfurt", countryCode: "DE", countryName: "Germany" },
  { iataCode: "MUC", name: "Munich Airport", cityName: "Munich", countryCode: "DE", countryName: "Germany" },
  { iataCode: "TXL", name: "Berlin Brandenburg Airport", cityName: "Berlin", countryCode: "DE", countryName: "Germany" },
  { iataCode: "BER", name: "Berlin Brandenburg Airport", cityName: "Berlin", countryCode: "DE", countryName: "Germany" },
  { iataCode: "MAD", name: "Adolfo Suárez Madrid–Barajas Airport", cityName: "Madrid", countryCode: "ES", countryName: "Spain" },
  { iataCode: "BCN", name: "Barcelona–El Prat Airport", cityName: "Barcelona", countryCode: "ES", countryName: "Spain" },
  { iataCode: "FCO", name: "Leonardo da Vinci–Fiumicino Airport", cityName: "Rome", countryCode: "IT", countryName: "Italy" },
  { iataCode: "MXP", name: "Milan Malpensa Airport", cityName: "Milan", countryCode: "IT", countryName: "Italy" },
  { iataCode: "ZRH", name: "Zurich Airport", cityName: "Zurich", countryCode: "CH", countryName: "Switzerland" },
  { iataCode: "VIE", name: "Vienna International Airport", cityName: "Vienna", countryCode: "AT", countryName: "Austria" },
  { iataCode: "BRU", name: "Brussels Airport", cityName: "Brussels", countryCode: "BE", countryName: "Belgium" },
  { iataCode: "CPH", name: "Copenhagen Airport", cityName: "Copenhagen", countryCode: "DK", countryName: "Denmark" },
  { iataCode: "ARN", name: "Stockholm Arlanda Airport", cityName: "Stockholm", countryCode: "SE", countryName: "Sweden" },
  { iataCode: "OSL", name: "Oslo Airport, Gardermoen", cityName: "Oslo", countryCode: "NO", countryName: "Norway" },
  { iataCode: "HEL", name: "Helsinki Airport", cityName: "Helsinki", countryCode: "FI", countryName: "Finland" },
  { iataCode: "LIS", name: "Humberto Delgado Airport", cityName: "Lisbon", countryCode: "PT", countryName: "Portugal" },
  { iataCode: "DUB", name: "Dublin Airport", cityName: "Dublin", countryCode: "IE", countryName: "Ireland" },
  { iataCode: "ATH", name: "Athens International Airport", cityName: "Athens", countryCode: "GR", countryName: "Greece" },
  { iataCode: "WAW", name: "Warsaw Chopin Airport", cityName: "Warsaw", countryCode: "PL", countryName: "Poland" },
  { iataCode: "PRG", name: "Václav Havel Airport Prague", cityName: "Prague", countryCode: "CZ", countryName: "Czech Republic" },
  { iataCode: "BUD", name: "Budapest Ferenc Liszt International Airport", cityName: "Budapest", countryCode: "HU", countryName: "Hungary" },
  { iataCode: "SVO", name: "Sheremetyevo International Airport", cityName: "Moscow", countryCode: "RU", countryName: "Russia" },
  // ── North America ───────────────────────────────────
  { iataCode: "JFK", name: "John F. Kennedy International Airport", cityName: "New York", countryCode: "US", countryName: "United States" },
  { iataCode: "EWR", name: "Newark Liberty International Airport", cityName: "New York", countryCode: "US", countryName: "United States" },
  { iataCode: "LGA", name: "LaGuardia Airport", cityName: "New York", countryCode: "US", countryName: "United States" },
  { iataCode: "LAX", name: "Los Angeles International Airport", cityName: "Los Angeles", countryCode: "US", countryName: "United States" },
  { iataCode: "SFO", name: "San Francisco International Airport", cityName: "San Francisco", countryCode: "US", countryName: "United States" },
  { iataCode: "SJC", name: "Norman Y. Mineta San Jose International Airport", cityName: "San Jose", countryCode: "US", countryName: "United States" },
  { iataCode: "OAK", name: "Oakland International Airport", cityName: "Oakland", countryCode: "US", countryName: "United States" },
  { iataCode: "ORD", name: "O'Hare International Airport", cityName: "Chicago", countryCode: "US", countryName: "United States" },
  { iataCode: "MDW", name: "Chicago Midway International Airport", cityName: "Chicago", countryCode: "US", countryName: "United States" },
  { iataCode: "ATL", name: "Hartsfield–Jackson Atlanta International Airport", cityName: "Atlanta", countryCode: "US", countryName: "United States" },
  { iataCode: "DFW", name: "Dallas/Fort Worth International Airport", cityName: "Dallas", countryCode: "US", countryName: "United States" },
  { iataCode: "IAH", name: "George Bush Intercontinental Airport", cityName: "Houston", countryCode: "US", countryName: "United States" },
  { iataCode: "MIA", name: "Miami International Airport", cityName: "Miami", countryCode: "US", countryName: "United States" },
  { iataCode: "BOS", name: "Boston Logan International Airport", cityName: "Boston", countryCode: "US", countryName: "United States" },
  { iataCode: "SEA", name: "Seattle-Tacoma International Airport", cityName: "Seattle", countryCode: "US", countryName: "United States" },
  { iataCode: "DEN", name: "Denver International Airport", cityName: "Denver", countryCode: "US", countryName: "United States" },
  { iataCode: "LAS", name: "Harry Reid International Airport", cityName: "Las Vegas", countryCode: "US", countryName: "United States" },
  { iataCode: "PHX", name: "Phoenix Sky Harbor International Airport", cityName: "Phoenix", countryCode: "US", countryName: "United States" },
  { iataCode: "MSP", name: "Minneapolis–Saint Paul International Airport", cityName: "Minneapolis", countryCode: "US", countryName: "United States" },
  { iataCode: "DTW", name: "Detroit Metropolitan Airport", cityName: "Detroit", countryCode: "US", countryName: "United States" },
  { iataCode: "IAD", name: "Washington Dulles International Airport", cityName: "Washington D.C.", countryCode: "US", countryName: "United States" },
  { iataCode: "DCA", name: "Ronald Reagan Washington National Airport", cityName: "Washington D.C.", countryCode: "US", countryName: "United States" },
  { iataCode: "PDX", name: "Portland International Airport", cityName: "Portland", countryCode: "US", countryName: "United States" },
  { iataCode: "HNL", name: "Daniel K. Inouye International Airport", cityName: "Honolulu", countryCode: "US", countryName: "United States" },
  { iataCode: "ANC", name: "Ted Stevens Anchorage International Airport", cityName: "Anchorage", countryCode: "US", countryName: "United States" },
  { iataCode: "YYZ", name: "Toronto Pearson International Airport", cityName: "Toronto", countryCode: "CA", countryName: "Canada" },
  { iataCode: "YVR", name: "Vancouver International Airport", cityName: "Vancouver", countryCode: "CA", countryName: "Canada" },
  { iataCode: "YUL", name: "Montréal–Trudeau International Airport", cityName: "Montreal", countryCode: "CA", countryName: "Canada" },
  { iataCode: "YYC", name: "Calgary International Airport", cityName: "Calgary", countryCode: "CA", countryName: "Canada" },
  { iataCode: "MEX", name: "Mexico City International Airport", cityName: "Mexico City", countryCode: "MX", countryName: "Mexico" },
  { iataCode: "CUN", name: "Cancún International Airport", cityName: "Cancún", countryCode: "MX", countryName: "Mexico" },
  // ── Oceania ─────────────────────────────────────────
  { iataCode: "SYD", name: "Sydney Kingsford Smith Airport", cityName: "Sydney", countryCode: "AU", countryName: "Australia" },
  { iataCode: "MEL", name: "Melbourne Airport", cityName: "Melbourne", countryCode: "AU", countryName: "Australia" },
  { iataCode: "BNE", name: "Brisbane Airport", cityName: "Brisbane", countryCode: "AU", countryName: "Australia" },
  { iataCode: "PER", name: "Perth Airport", cityName: "Perth", countryCode: "AU", countryName: "Australia" },
  { iataCode: "AKL", name: "Auckland Airport", cityName: "Auckland", countryCode: "NZ", countryName: "New Zealand" },
  { iataCode: "CHC", name: "Christchurch Airport", cityName: "Christchurch", countryCode: "NZ", countryName: "New Zealand" },
  // ── Africa ──────────────────────────────────────────
  { iataCode: "JNB", name: "O.R. Tambo International Airport", cityName: "Johannesburg", countryCode: "ZA", countryName: "South Africa" },
  { iataCode: "CPT", name: "Cape Town International Airport", cityName: "Cape Town", countryCode: "ZA", countryName: "South Africa" },
  { iataCode: "CAI", name: "Cairo International Airport", cityName: "Cairo", countryCode: "EG", countryName: "Egypt" },
  { iataCode: "NBO", name: "Jomo Kenyatta International Airport", cityName: "Nairobi", countryCode: "KE", countryName: "Kenya" },
  { iataCode: "ADD", name: "Addis Ababa Bole International Airport", cityName: "Addis Ababa", countryCode: "ET", countryName: "Ethiopia" },
  { iataCode: "CMN", name: "Mohammed V International Airport", cityName: "Casablanca", countryCode: "MA", countryName: "Morocco" },
  // ── South America ───────────────────────────────────
  { iataCode: "GRU", name: "São Paulo–Guarulhos International Airport", cityName: "São Paulo", countryCode: "BR", countryName: "Brazil" },
  { iataCode: "GIG", name: "Rio de Janeiro–Galeão International Airport", cityName: "Rio de Janeiro", countryCode: "BR", countryName: "Brazil" },
  { iataCode: "EZE", name: "Ministro Pistarini International Airport", cityName: "Buenos Aires", countryCode: "AR", countryName: "Argentina" },
  { iataCode: "SCL", name: "Santiago Arturo Merino Benítez International Airport", cityName: "Santiago", countryCode: "CL", countryName: "Chile" },
  { iataCode: "BOG", name: "El Dorado International Airport", cityName: "Bogotá", countryCode: "CO", countryName: "Colombia" },
  { iataCode: "LIM", name: "Jorge Chávez International Airport", cityName: "Lima", countryCode: "PE", countryName: "Peru" },
];

/** Search airports by keyword (IATA code, name, city name, or country name). */
export function searchAirports(keyword: string): AirportOption[] {
  const kw = keyword.toLowerCase().trim();
  if (kw.length < 2) return [];

  return AIRPORTS.filter(
    (a) =>
      a.iataCode.toLowerCase().includes(kw) ||
      a.name.toLowerCase().includes(kw) ||
      a.cityName.toLowerCase().includes(kw) ||
      a.countryCode.toLowerCase() === kw ||
      a.countryName.toLowerCase().includes(kw)
  ).slice(0, 8);
}
