import type { AirportOption } from "./types";

/** Static list of major world airports for autocomplete (no API call needed). */
export const AIRPORTS: AirportOption[] = [
  // ── Taiwan ──────────────────────────────────────────
  { iataCode: "TPE", name: "Taiwan Taoyuan International Airport", cityName: "Taipei", countryCode: "TW" },
  { iataCode: "TSA", name: "Taipei Songshan Airport", cityName: "Taipei", countryCode: "TW" },
  { iataCode: "KHH", name: "Kaohsiung International Airport", cityName: "Kaohsiung", countryCode: "TW" },
  // ── East Asia ───────────────────────────────────────
  { iataCode: "NRT", name: "Narita International Airport", cityName: "Tokyo", countryCode: "JP" },
  { iataCode: "HND", name: "Tokyo Haneda Airport", cityName: "Tokyo", countryCode: "JP" },
  { iataCode: "KIX", name: "Kansai International Airport", cityName: "Osaka", countryCode: "JP" },
  { iataCode: "ITM", name: "Osaka Itami Airport", cityName: "Osaka", countryCode: "JP" },
  { iataCode: "FUK", name: "Fukuoka Airport", cityName: "Fukuoka", countryCode: "JP" },
  { iataCode: "CTS", name: "New Chitose Airport", cityName: "Sapporo", countryCode: "JP" },
  { iataCode: "NGO", name: "Chubu Centrair International Airport", cityName: "Nagoya", countryCode: "JP" },
  { iataCode: "OKA", name: "Naha Airport", cityName: "Okinawa", countryCode: "JP" },
  { iataCode: "ICN", name: "Incheon International Airport", cityName: "Seoul", countryCode: "KR" },
  { iataCode: "GMP", name: "Gimpo International Airport", cityName: "Seoul", countryCode: "KR" },
  { iataCode: "PUS", name: "Gimhae International Airport", cityName: "Busan", countryCode: "KR" },
  { iataCode: "HKG", name: "Hong Kong International Airport", cityName: "Hong Kong", countryCode: "HK" },
  { iataCode: "PVG", name: "Shanghai Pudong International Airport", cityName: "Shanghai", countryCode: "CN" },
  { iataCode: "SHA", name: "Shanghai Hongqiao International Airport", cityName: "Shanghai", countryCode: "CN" },
  { iataCode: "PEK", name: "Beijing Capital International Airport", cityName: "Beijing", countryCode: "CN" },
  { iataCode: "PKX", name: "Beijing Daxing International Airport", cityName: "Beijing", countryCode: "CN" },
  { iataCode: "CAN", name: "Guangzhou Baiyun International Airport", cityName: "Guangzhou", countryCode: "CN" },
  { iataCode: "SZX", name: "Shenzhen Bao'an International Airport", cityName: "Shenzhen", countryCode: "CN" },
  { iataCode: "CTU", name: "Chengdu Shuangliu International Airport", cityName: "Chengdu", countryCode: "CN" },
  { iataCode: "XIY", name: "Xi'an Xianyang International Airport", cityName: "Xi'an", countryCode: "CN" },
  { iataCode: "MFM", name: "Macau International Airport", cityName: "Macau", countryCode: "MO" },
  // ── Southeast Asia ──────────────────────────────────
  { iataCode: "BKK", name: "Suvarnabhumi Airport", cityName: "Bangkok", countryCode: "TH" },
  { iataCode: "DMK", name: "Don Mueang International Airport", cityName: "Bangkok", countryCode: "TH" },
  { iataCode: "HKT", name: "Phuket International Airport", cityName: "Phuket", countryCode: "TH" },
  { iataCode: "CNX", name: "Chiang Mai International Airport", cityName: "Chiang Mai", countryCode: "TH" },
  { iataCode: "SIN", name: "Singapore Changi Airport", cityName: "Singapore", countryCode: "SG" },
  { iataCode: "KUL", name: "Kuala Lumpur International Airport", cityName: "Kuala Lumpur", countryCode: "MY" },
  { iataCode: "CGK", name: "Soekarno-Hatta International Airport", cityName: "Jakarta", countryCode: "ID" },
  { iataCode: "DPS", name: "Ngurah Rai International Airport", cityName: "Bali", countryCode: "ID" },
  { iataCode: "MNL", name: "Ninoy Aquino International Airport", cityName: "Manila", countryCode: "PH" },
  { iataCode: "CEB", name: "Mactan–Cebu International Airport", cityName: "Cebu", countryCode: "PH" },
  { iataCode: "SGN", name: "Tan Son Nhat International Airport", cityName: "Ho Chi Minh City", countryCode: "VN" },
  { iataCode: "HAN", name: "Noi Bai International Airport", cityName: "Hanoi", countryCode: "VN" },
  { iataCode: "DAD", name: "Da Nang International Airport", cityName: "Da Nang", countryCode: "VN" },
  { iataCode: "RGN", name: "Yangon International Airport", cityName: "Yangon", countryCode: "MM" },
  { iataCode: "PNH", name: "Phnom Penh International Airport", cityName: "Phnom Penh", countryCode: "KH" },
  // ── South Asia ──────────────────────────────────────
  { iataCode: "DEL", name: "Indira Gandhi International Airport", cityName: "New Delhi", countryCode: "IN" },
  { iataCode: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", cityName: "Mumbai", countryCode: "IN" },
  { iataCode: "BLR", name: "Kempegowda International Airport", cityName: "Bangalore", countryCode: "IN" },
  { iataCode: "MAA", name: "Chennai International Airport", cityName: "Chennai", countryCode: "IN" },
  { iataCode: "CMB", name: "Bandaranaike International Airport", cityName: "Colombo", countryCode: "LK" },
  { iataCode: "DAC", name: "Hazrat Shahjalal International Airport", cityName: "Dhaka", countryCode: "BD" },
  { iataCode: "KTM", name: "Tribhuvan International Airport", cityName: "Kathmandu", countryCode: "NP" },
  // ── Middle East ─────────────────────────────────────
  { iataCode: "DXB", name: "Dubai International Airport", cityName: "Dubai", countryCode: "AE" },
  { iataCode: "AUH", name: "Abu Dhabi International Airport", cityName: "Abu Dhabi", countryCode: "AE" },
  { iataCode: "DOH", name: "Hamad International Airport", cityName: "Doha", countryCode: "QA" },
  { iataCode: "IST", name: "Istanbul Airport", cityName: "Istanbul", countryCode: "TR" },
  { iataCode: "SAW", name: "Istanbul Sabiha Gökçen International Airport", cityName: "Istanbul", countryCode: "TR" },
  { iataCode: "TLV", name: "Ben Gurion International Airport", cityName: "Tel Aviv", countryCode: "IL" },
  // ── Europe ──────────────────────────────────────────
  { iataCode: "LHR", name: "London Heathrow Airport", cityName: "London", countryCode: "GB" },
  { iataCode: "LGW", name: "London Gatwick Airport", cityName: "London", countryCode: "GB" },
  { iataCode: "STN", name: "London Stansted Airport", cityName: "London", countryCode: "GB" },
  { iataCode: "CDG", name: "Charles de Gaulle Airport", cityName: "Paris", countryCode: "FR" },
  { iataCode: "ORY", name: "Paris Orly Airport", cityName: "Paris", countryCode: "FR" },
  { iataCode: "AMS", name: "Amsterdam Airport Schiphol", cityName: "Amsterdam", countryCode: "NL" },
  { iataCode: "FRA", name: "Frankfurt Airport", cityName: "Frankfurt", countryCode: "DE" },
  { iataCode: "MUC", name: "Munich Airport", cityName: "Munich", countryCode: "DE" },
  { iataCode: "TXL", name: "Berlin Brandenburg Airport", cityName: "Berlin", countryCode: "DE" },
  { iataCode: "BER", name: "Berlin Brandenburg Airport", cityName: "Berlin", countryCode: "DE" },
  { iataCode: "MAD", name: "Adolfo Suárez Madrid–Barajas Airport", cityName: "Madrid", countryCode: "ES" },
  { iataCode: "BCN", name: "Barcelona–El Prat Airport", cityName: "Barcelona", countryCode: "ES" },
  { iataCode: "FCO", name: "Leonardo da Vinci–Fiumicino Airport", cityName: "Rome", countryCode: "IT" },
  { iataCode: "MXP", name: "Milan Malpensa Airport", cityName: "Milan", countryCode: "IT" },
  { iataCode: "ZRH", name: "Zurich Airport", cityName: "Zurich", countryCode: "CH" },
  { iataCode: "VIE", name: "Vienna International Airport", cityName: "Vienna", countryCode: "AT" },
  { iataCode: "BRU", name: "Brussels Airport", cityName: "Brussels", countryCode: "BE" },
  { iataCode: "CPH", name: "Copenhagen Airport", cityName: "Copenhagen", countryCode: "DK" },
  { iataCode: "ARN", name: "Stockholm Arlanda Airport", cityName: "Stockholm", countryCode: "SE" },
  { iataCode: "OSL", name: "Oslo Airport, Gardermoen", cityName: "Oslo", countryCode: "NO" },
  { iataCode: "HEL", name: "Helsinki Airport", cityName: "Helsinki", countryCode: "FI" },
  { iataCode: "LIS", name: "Humberto Delgado Airport", cityName: "Lisbon", countryCode: "PT" },
  { iataCode: "DUB", name: "Dublin Airport", cityName: "Dublin", countryCode: "IE" },
  { iataCode: "ATH", name: "Athens International Airport", cityName: "Athens", countryCode: "GR" },
  { iataCode: "WAW", name: "Warsaw Chopin Airport", cityName: "Warsaw", countryCode: "PL" },
  { iataCode: "PRG", name: "Václav Havel Airport Prague", cityName: "Prague", countryCode: "CZ" },
  { iataCode: "BUD", name: "Budapest Ferenc Liszt International Airport", cityName: "Budapest", countryCode: "HU" },
  { iataCode: "SVO", name: "Sheremetyevo International Airport", cityName: "Moscow", countryCode: "RU" },
  // ── North America ───────────────────────────────────
  { iataCode: "JFK", name: "John F. Kennedy International Airport", cityName: "New York", countryCode: "US" },
  { iataCode: "EWR", name: "Newark Liberty International Airport", cityName: "New York", countryCode: "US" },
  { iataCode: "LGA", name: "LaGuardia Airport", cityName: "New York", countryCode: "US" },
  { iataCode: "LAX", name: "Los Angeles International Airport", cityName: "Los Angeles", countryCode: "US" },
  { iataCode: "SFO", name: "San Francisco International Airport", cityName: "San Francisco", countryCode: "US" },
  { iataCode: "SJC", name: "Norman Y. Mineta San Jose International Airport", cityName: "San Jose", countryCode: "US" },
  { iataCode: "OAK", name: "Oakland International Airport", cityName: "Oakland", countryCode: "US" },
  { iataCode: "ORD", name: "O'Hare International Airport", cityName: "Chicago", countryCode: "US" },
  { iataCode: "MDW", name: "Chicago Midway International Airport", cityName: "Chicago", countryCode: "US" },
  { iataCode: "ATL", name: "Hartsfield–Jackson Atlanta International Airport", cityName: "Atlanta", countryCode: "US" },
  { iataCode: "DFW", name: "Dallas/Fort Worth International Airport", cityName: "Dallas", countryCode: "US" },
  { iataCode: "IAH", name: "George Bush Intercontinental Airport", cityName: "Houston", countryCode: "US" },
  { iataCode: "MIA", name: "Miami International Airport", cityName: "Miami", countryCode: "US" },
  { iataCode: "BOS", name: "Boston Logan International Airport", cityName: "Boston", countryCode: "US" },
  { iataCode: "SEA", name: "Seattle-Tacoma International Airport", cityName: "Seattle", countryCode: "US" },
  { iataCode: "DEN", name: "Denver International Airport", cityName: "Denver", countryCode: "US" },
  { iataCode: "LAS", name: "Harry Reid International Airport", cityName: "Las Vegas", countryCode: "US" },
  { iataCode: "PHX", name: "Phoenix Sky Harbor International Airport", cityName: "Phoenix", countryCode: "US" },
  { iataCode: "MSP", name: "Minneapolis–Saint Paul International Airport", cityName: "Minneapolis", countryCode: "US" },
  { iataCode: "DTW", name: "Detroit Metropolitan Airport", cityName: "Detroit", countryCode: "US" },
  { iataCode: "IAD", name: "Washington Dulles International Airport", cityName: "Washington D.C.", countryCode: "US" },
  { iataCode: "DCA", name: "Ronald Reagan Washington National Airport", cityName: "Washington D.C.", countryCode: "US" },
  { iataCode: "PDX", name: "Portland International Airport", cityName: "Portland", countryCode: "US" },
  { iataCode: "HNL", name: "Daniel K. Inouye International Airport", cityName: "Honolulu", countryCode: "US" },
  { iataCode: "ANC", name: "Ted Stevens Anchorage International Airport", cityName: "Anchorage", countryCode: "US" },
  { iataCode: "YYZ", name: "Toronto Pearson International Airport", cityName: "Toronto", countryCode: "CA" },
  { iataCode: "YVR", name: "Vancouver International Airport", cityName: "Vancouver", countryCode: "CA" },
  { iataCode: "YUL", name: "Montréal–Trudeau International Airport", cityName: "Montreal", countryCode: "CA" },
  { iataCode: "YYC", name: "Calgary International Airport", cityName: "Calgary", countryCode: "CA" },
  { iataCode: "MEX", name: "Mexico City International Airport", cityName: "Mexico City", countryCode: "MX" },
  { iataCode: "CUN", name: "Cancún International Airport", cityName: "Cancún", countryCode: "MX" },
  // ── Oceania ─────────────────────────────────────────
  { iataCode: "SYD", name: "Sydney Kingsford Smith Airport", cityName: "Sydney", countryCode: "AU" },
  { iataCode: "MEL", name: "Melbourne Airport", cityName: "Melbourne", countryCode: "AU" },
  { iataCode: "BNE", name: "Brisbane Airport", cityName: "Brisbane", countryCode: "AU" },
  { iataCode: "PER", name: "Perth Airport", cityName: "Perth", countryCode: "AU" },
  { iataCode: "AKL", name: "Auckland Airport", cityName: "Auckland", countryCode: "NZ" },
  { iataCode: "CHC", name: "Christchurch Airport", cityName: "Christchurch", countryCode: "NZ" },
  // ── Africa ──────────────────────────────────────────
  { iataCode: "JNB", name: "O.R. Tambo International Airport", cityName: "Johannesburg", countryCode: "ZA" },
  { iataCode: "CPT", name: "Cape Town International Airport", cityName: "Cape Town", countryCode: "ZA" },
  { iataCode: "CAI", name: "Cairo International Airport", cityName: "Cairo", countryCode: "EG" },
  { iataCode: "NBO", name: "Jomo Kenyatta International Airport", cityName: "Nairobi", countryCode: "KE" },
  { iataCode: "ADD", name: "Addis Ababa Bole International Airport", cityName: "Addis Ababa", countryCode: "ET" },
  { iataCode: "CMN", name: "Mohammed V International Airport", cityName: "Casablanca", countryCode: "MA" },
  // ── South America ───────────────────────────────────
  { iataCode: "GRU", name: "São Paulo–Guarulhos International Airport", cityName: "São Paulo", countryCode: "BR" },
  { iataCode: "GIG", name: "Rio de Janeiro–Galeão International Airport", cityName: "Rio de Janeiro", countryCode: "BR" },
  { iataCode: "EZE", name: "Ministro Pistarini International Airport", cityName: "Buenos Aires", countryCode: "AR" },
  { iataCode: "SCL", name: "Santiago Arturo Merino Benítez International Airport", cityName: "Santiago", countryCode: "CL" },
  { iataCode: "BOG", name: "El Dorado International Airport", cityName: "Bogotá", countryCode: "CO" },
  { iataCode: "LIM", name: "Jorge Chávez International Airport", cityName: "Lima", countryCode: "PE" },
];

/** Search airports by keyword (IATA code, name, or city name). */
export function searchAirports(keyword: string): AirportOption[] {
  const kw = keyword.toLowerCase().trim();
  if (kw.length < 2) return [];

  return AIRPORTS.filter(
    (a) =>
      a.iataCode.toLowerCase().includes(kw) ||
      a.name.toLowerCase().includes(kw) ||
      a.cityName.toLowerCase().includes(kw) ||
      a.countryCode.toLowerCase() === kw
  ).slice(0, 8);
}
